#!/bin/sh

# PROVIDE: BitSmart
# REQUIRE: LOGIN
# KEYWORD: shutdown

#
# Add the following lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# BitSmart_enable (bool): Set to NO by default. Set this variable to YES if you want to enable BitSmart service.
# BitSmart_config (path): Set to /usr/local/etc/BitSmart.conf by default.
# BitSmart_user:  The user account BitSmart daemon runs as. It uses 'root' user by default.
# BitSmart_group: The group account BitSmart daemon runs as. It uses 'wheel' group by default.
# BitSmart_datadir (str): Default to "/var/db/BitSmart". Base data directory.

. /etc/rc.subr

name=BitSmart
rcvar=BitSmart_enable

: ${BitSmart_enable:=NO}
: ${BitSmart_config=/usr/local/etc/BitSmart.conf}
: ${BitSmart_datadir=/var/db/BitSmart}
: ${BitSmart_user="root"}
: ${BitSmart_group="wheel"}

required_files=${BitSmart_config}
command=/usr/local/bin/BitSmartd
BitSmart_chdir=${BitSmart_datadir}
pidfile="${BitSmart_datadir}/BitSmartd.pid"
stop_cmd=BitSmart_stop
command_args="-conf=${BitSmart_config} -datadir=${BitSmart_datadir} -daemon -pid=${pidfile}"
start_precmd="${name}_prestart"

BitSmart_create_datadir()
{
	echo "Creating data directory"
	eval mkdir -p ${BitSmart_datadir}
	[ $? -eq 0 ] && chown -R ${BitSmart_user}:${BitSmart_group} ${BitSmart_datadir}
}

BitSmart_prestart()
{
	if [ ! -d "${BitSmart_datadir}/." ]; then
		BitSmart_create_datadir || return 1
	fi
}

BitSmart_requirepidfile()
{
	if [ ! "0`check_pidfile ${pidfile} ${command}`" -gt 1 ]; then
		echo "${name} not running? (check $pidfile)."
		exit 1
	fi
}

BitSmart_stop()
{
    BitSmart_requirepidfile

	echo "Stopping ${name}."
	eval ${command} -conf=${BitSmart_config} -datadir=${BitSmart_datadir} stop
	wait_for_pids ${rc_pid}
}

load_rc_config $name
run_rc_command "$1"
